#!/sbin/bash

mkdir -p tmp;
mkdir -p exframes;

if [[ $# -ge 1 ]]; then

  # Encode File
  if [[ $1 == "-e" ]]; then
    ruby encoder.rb $2
    convert -delay 10 -loop 0 ./tmp/*.png rgbqr.gif

  elif [[ $1 == "-scan" ]]; then
    python ./capture.py

  elif [[ $1 == "-track" ]]; then
    python ./mouse.py &
    
  fi

fi